name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 1G \
              --repositories-file openstack/repositories \
              --packages "$(cat openstack/packages)" \
              --script-chroot \
              alpine-openstack.qcow2 -- ./openstack/configure.sh
          sha256sum alpine-openstack.qcow2 | cut -d' ' -f 1 > alpine-openstack.qcow2.sha256
      - name: Upload root fs artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-openstack.qcow2
          path: "${{ github.workspace }}/alpine-openstack.qcow2"
      - name: Make Development release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            alpine-openstack.qcow2
            alpine-openstack.qcow2.sha256
